def sum(x, y):
    return x + y


def myfunc_error():
    raise ValueError("Exception 123 raised")
